name: publish

on:
  release:
    types: [published]
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # required for JSR OIDC

concurrency:
  group: publish-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm -s vitest run -w --reporter=dot
        env: { CI: true }

      # npm publish
      - name: Set npm auth
        run: |
          npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to npm
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ "$VERSION" == *-* ]]; then
            pnpm publish --access public --no-git-checks --tag next
          else
            pnpm publish --access public --no-git-checks
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # JSR publish (OIDC, no secret needed once linked)
      - name: Publish to JSR
        run: pnpm dlx jsr publish
